name : natron

uuid : 017a77ab-76e9-4a14-8fb6-b3052103f7b2

description : "Natron is an open-source, crossplatform nodal, compositing software"
authors : [inria]
config_version : 0
version : 1.0.0

commands:
- export PATH=$BD_SOFTS/natron/!VERSION!:$PATH
